name: nian
favicon: null
layout_spectrum: 0.33658
typography_spectrum: 0.73603
title: Nian.NET
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#606060'
    - '#373737'
    - '#ababab'
  brandStrength: 0.4375
  lightness: 0.39482247736305
  saturation: 0.3714373118709773
  rhythmicContrast: 0.014441122766584158
purpose: []
